
import { Translation, Product, Campaign, NGO, Language, Transaction, ChatContact } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    app_name: "Educycle",
    nav_dashboard: "Dashboard",
    nav_profile: "My Profile",
    nav_settings: "Settings",
    nav_marketplace: "Marketplace",
    nav_sell: "Sell Item",
    nav_campaigns: "All Campaigns",
    nav_my_campaigns: "My Campaigns",
    nav_donate: "Donate",
    nav_chat: "Messages",
    nav_notifications: "Notifications",
    nav_cart: "My Cart",
    role_switch: "Mode",

    hero_title: "Educycle Marketplace",
    hero_subtitle: "The sustainable student community for buying, selling, and volunteering.",

    sell_page_title: "List Item for Sale",
    sell_upload_image: "Upload Item Image",
    sell_generating: "AI Analyzing...",
    sell_generate_desc: "AI-generated description",
    sell_voice_hint: "All fields support voice input",
    form_title: "Item Title",
    form_price: "Price (₹)",
    form_desc: "Description",
    form_category: "Category",
    form_submit: "List Item",

    dashboard_earnings: "Total Earnings",
    dashboard_transactions: "Recent Transactions",
    dashboard_sold: "Sold Inventory",

    profile_bio: "Bio",
    profile_name: "Full Name",
    profile_email: "Email",
    profile_avatar: "Profile Picture URL",
    profile_save: "Save Profile",
    profile_edit: "Edit Profile",
    profile_cancel: "Cancel",
    profile_history: "Purchase History",
    profile_history_empty: "No items purchased yet.",

    settings_title: "Account Settings",
    settings_save: "Save Changes",
    settings_saved: "Your changes have been saved.",

    campaign_join: "Join Event",
    campaign_register_title: "Register for Event",
    campaign_register_btn: "Confirm Registration",
    campaign_search: "Search campaigns by name or keyword...",
    campaign_create: "+ Create Campaign",
    campaign_report: "Report",
    campaign_reported: "Reported",

    donate_title: "Donation Drives",
    donate_btn: "Donate Item",
    donate_form_title: "Donation Pledge Form",
    donate_confirm: "Confirm Donation",
    donate_item_label: "What are you donating?",
    donate_pickup_label: "Pickup Address",
    donate_thanks: "Thank you for your donation pledge!",

    chat_title: "Messages",
    chat_placeholder: "Type a message...",
    negotiate_offer: "Make Offer",
    offer_sent: "Offer Sent",
    offer_accept: "Accept",
    offer_reject: "Reject",
    offer_status_accepted: "Offer Accepted",
    offer_status_rejected: "Offer Rejected",

    home_welcome: "Welcome to Educycle",
    home_sub: "Your campus community for buying, selling, and giving back.",
    home_btn_start: "Get Started",
    home_login: "Login",
    home_signup: "Sign Up",
    auth_login_title: "Login to your account",
    auth_signup_title: "Create an account",
    auth_email: "Email Address",
    auth_password: "Password",
    auth_name: "Full Name",
    auth_btn_login: "Sign In",
    auth_btn_signup: "Sign Up",
    auth_have_acc: "Already have an account? Login",
    auth_no_acc: "Don't have an account? Sign Up",

    landing_features_title: "What You Can Do",
    landing_feature_market_title: "Student Marketplace",
    landing_feature_market_desc: "Buy and sell used textbooks, electronics, and stationary directly from other students.",
    landing_feature_campaign_title: "Community Campaigns",
    landing_feature_campaign_desc: "Join river cleaning, park maintenance, and recycling drives to keep our environment green.",
    landing_feature_donate_title: "Donation Drives",
    landing_feature_donate_desc: "Support local NGOs by donating clothes, books, and essentials to those in need.",
    landing_footer_about: "Educycle",
    landing_footer_contact: "Contact Us",
    landing_footer_rights: "All rights reserved.",

    cart_title: "Your Cart",
    cart_empty: "Your cart is empty",
    cart_total: "Total Amount",
    cart_checkout: "Proceed to Checkout",
    checkout_title: "Checkout",
    pay_upi: "UPI (GPay/PhonePe)",
    pay_card: "Credit/Debit Card",
    pay_cod: "Cash on Delivery",
    pay_btn: "Place Order",
    order_success: "Order Confirmed!",
    order_cod_msg: "Please be ready with cash or UPI upon delivery.",
    order_online_msg: "Thank you for your payment. Your order is being processed."
  },
  hi: {
    app_name: "Educycle",
    nav_dashboard: "डैशबोर्ड",
    nav_profile: "मेरी प्रोफ़ाइल",
    nav_settings: "सेटिंग्स",
    nav_marketplace: "बाज़ार",
    nav_sell: "बेचें",
    nav_campaigns: "अभियान",
    nav_my_campaigns: "मेरे अभियान",
    nav_donate: "दान",
    nav_chat: "संदेश",
    nav_notifications: "सूचनाएं",
    nav_cart: "मेरी कार्ट",
    role_switch: "मोड",

    hero_title: "Educycle बाज़ार",
    hero_subtitle: "छात्रों के लिए स्थायी समुदाय।",

    sell_page_title: "बिक्री के लिए सूची",
    sell_upload_image: "तस्वीर अपलोड करें",
    sell_generating: "AI विश्लेषण...",
    sell_generate_desc: "AI-generated description",
    sell_voice_hint: "सभी फ़ील्ड में वॉयस इनपुट है",
    form_title: "शीर्षक",
    form_price: "कीमत (₹)",
    form_desc: "विवरण",
    form_category: "श्रेणी",
    form_submit: "सूचीबद्ध करें",

    dashboard_earnings: "कुल कमाई",
    dashboard_transactions: "हालिया लेनदेन",
    dashboard_sold: "बिकी हुई वस्तुएं",

    profile_bio: "बायो",
    profile_name: "पूरा नाम",
    profile_email: "ईमेल",
    profile_avatar: "प्रोफ़ाइल चित्र URL",
    profile_save: "सहेजें",
    profile_edit: "प्रोफ़ाइल संपादित करें",
    profile_cancel: "रद्द करें",
    profile_history: "खरीद इतिहास",
    profile_history_empty: "अभी तक कोई वस्तु नहीं खरीदी गई।",

    settings_title: "खाता सेटिंग्स",
    settings_save: "परिवर्तन सहेजें",
    settings_saved: "आपके परिवर्तन सहेजे गए हैं।",

    campaign_join: "जुड़ें",
    campaign_register_title: "पंजीकरण करें",
    campaign_register_btn: "पुष्टि करें",
    campaign_search: "नाम या कीवर्ड से खोजें...",
    campaign_create: "+ अभियान बनाएं",
    campaign_report: "रिपोर्ट करें",
    campaign_reported: "रिपोर्ट किया गया",

    donate_title: "दान अभियान",
    donate_btn: "दान करें",
    donate_form_title: "दान प्रतिज्ञा प्रपत्र",
    donate_confirm: "दान की पुष्टि करें",
    donate_item_label: "आप क्या दान कर रहे हैं?",
    donate_pickup_label: "पिकअप पता",
    donate_thanks: "आपके दान प्रतिज्ञा के लिए धन्यवाद!",

    chat_title: "चैट",
    chat_placeholder: "संदेश टाइप करें...",
    negotiate_offer: "प्रस्ताव दें",
    offer_sent: "प्रस्ताव भेजा गया",
    offer_accept: "स्वीकार करें",
    offer_reject: "अस्वीकार करें",
    offer_status_accepted: "प्रस्ताव स्वीकार कर लिया",
    offer_status_rejected: "प्रस्ताव अस्वीकार कर दिया",

    home_welcome: "Educycle में आपका स्वागत है",
    home_sub: "खरीदने, बेचने और वापस देने के लिए आपका कैंपस समुदाय।",
    home_btn_start: "शुरू करें",
    home_login: "लॉग इन करें",
    home_signup: "साइन अप करें",
    auth_login_title: "अपने खाते में लॉग इन करें",
    auth_signup_title: "खाता बनाएं",
    auth_email: "ईमेल पता",
    auth_password: "पासवर्ड",
    auth_name: "पूरा नाम",
    auth_btn_login: "साइन इन करें",
    auth_btn_signup: "साइन अप करें",
    auth_have_acc: "क्या आपके पास पहले से एक खाता मौजूद है? लॉग इन करें",
    auth_no_acc: "खाता नहीं है? साइन अप करें",

    landing_features_title: "आप क्या कर सकते हैं",
    landing_feature_market_title: "छात्र बाज़ार",
    landing_feature_market_desc: "अन्य छात्रों से सीधे पुरानी किताबें और इलेक्ट्रॉनिक्स खरीदें और बेचें।",
    landing_feature_campaign_title: "सामुદायिक अभियान",
    landing_feature_campaign_desc: "हमारे पर्यावरण को हरा-भरा रखने के लिए नदी सफाई और वृक्षारोपण में शामिल हों।",
    landing_feature_donate_title: "दान अभियान",
    landing_feature_donate_desc: "जरूरतमंदों को कपड़े और किताबें दान करके स्थानीय एनजीओ का समर्थन करें।",
    landing_footer_about: "Educycle के बारे में",
    landing_footer_contact: "संपर्क करें",
    landing_footer_rights: "सर्वाधिकार सुरक्षित।",

    cart_title: "आपकी कार्ट",
    cart_empty: "आपकी कार्ट खाली है",
    cart_total: "कुल राशि",
    cart_checkout: "चेकआउट करें",
    checkout_title: "चेकआउट",
    pay_upi: "UPI",
    pay_card: "कार्ड",
    pay_cod: "कैश ऑन डिलीवरी",
    pay_btn: "ऑर्डर करें",
    order_success: "ऑर्डर पक्का हो गया!",
    order_cod_msg: "कृपया डिलीवरी के समय नकद या UPI तैयार रखें।",
    order_online_msg: "भुगतान के लिए धन्यवाद। आपका ऑर्डर प्रोसेस किया जा रहा है।"
  },
  ta: {
    app_name: "Educycle",
    nav_dashboard: "டாஷ்போர்டு",
    nav_profile: "என் சுயவிவரம்",
    nav_settings: "அமைப்புகள்",
    nav_marketplace: "சந்தை",
    nav_sell: "விற்க",
    nav_campaigns: "பிரச்சாரங்கள்",
    nav_my_campaigns: "என் பிரச்சாரங்கள்",
    nav_donate: "நன்கொடை",
    nav_chat: "செய்திகள்",
    nav_notifications: "அறிவிப்புகள்",
    nav_cart: "கூடை",
    role_switch: "முறை",

    hero_title: "Educycle சந்தை",
    hero_subtitle: "மாணவர்களுக்கான நிலையான சமூகம்.",

    sell_page_title: "விற்பனைக்கு",
    sell_upload_image: "படம் பதிவேற்றவும்",
    sell_generating: "AI ஆய்வு...",
    sell_generate_desc: "AI-generated description",
    sell_voice_hint: "குரல் உள்ளீடு உள்ளது",
    form_title: "தலைப்பு",
    form_price: "விலை (₹)",
    form_desc: "விளக்கம்",
    form_category: "வகை",
    form_submit: "சமர்ப்பிக்கவும்",

    dashboard_earnings: "மொத்த வருவாய்",
    dashboard_transactions: "பரிவர்த்தனைகள்",
    dashboard_sold: "விற்கப்பட்டவை",

    profile_bio: "சுயவிவரம்",
    profile_name: "பெயர்",
    profile_email: "மின்னஞ்சல்",
    profile_avatar: "சுயவிவரப் படம்",
    profile_save: "சேமி",
    profile_edit: "திருத்த",
    profile_cancel: "ரத்து செய்",
    profile_history: "கொள்முதல் வரலாறு",
    profile_history_empty: "இதுவரை எதுவும் வாங்கவில்லை.",

    settings_title: "கணக்கு அமைப்புகள்",
    settings_save: "சேமிக்க",
    settings_saved: "உங்கள் மாற்றங்கள் சேமிக்கப்பட்டன.",

    campaign_join: "சேரவும்",
    campaign_register_title: "பதிவு செய்யவும்",
    campaign_register_btn: "உறுதிப்படுத்தவும்",
    campaign_search: "தேடுக...",
    campaign_create: "+ புதிய பிரச்சாரம்",
    campaign_report: "புகார்",
    campaign_reported: "புகாரளிக்கப்பட்டது",

    donate_title: "நன்கொடை இயக்கங்கள்",
    donate_btn: "நன்கொடை",
    donate_form_title: "நன்கொடை படிவம்",
    donate_confirm: "உறுதிப்படுத்தவும்",
    donate_item_label: "என்ன நன்கொடை அளிக்கிறீர்கள்?",
    donate_pickup_label: "முகவரி",
    donate_thanks: "நன்றி!",

    chat_title: "அரட்டை",
    chat_placeholder: "செய்தி...",
    negotiate_offer: "பேரம் பேசு",
    offer_sent: "சலுகை அனுப்பப்பட்டது",
    offer_accept: "ஏற்றுக்கொள்",
    offer_reject: "நிராகரி",
    offer_status_accepted: "ஏற்றுக்கொள்ளப்பட்டது",
    offer_status_rejected: "நிராகரிக்கப்பட்டது",

    home_welcome: "Educycleக்கு வரவேற்கிறோம்",
    home_sub: "வாங்க, விற்க மற்றும் திரும்பக் கொடுப்பதற்கான உங்கள் வளாக சமூகம்.",
    home_btn_start: "தொடங்கவும்",
    home_login: "உள்நுழைய",
    home_signup: "பதிவு செய்யவும்",
    auth_login_title: "உங்கள் கணக்கில் உள்நுழையவும்",
    auth_signup_title: "ஒரு கணக்கை உருவாக்கவும்",
    auth_email: "மின்னஞ்சல் முகவரி",
    auth_password: "கடவுச்சொல்",
    auth_name: "முழு பெயர்",
    auth_btn_login: "உள்நுழைய",
    auth_btn_signup: "பதிவு செய்யவும்",
    auth_have_acc: "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைய",
    auth_no_acc: "கணக்கு இல்லையா? பதிவு செய்யவும்",

    landing_features_title: "நீங்கள் என்ன செய்ய முடியும்",
    landing_feature_market_title: "மாணவர் சந்தை",
    landing_feature_market_desc: "பயன்படுத்தப்பட்ட புத்தகங்கள் மற்றும் பொருட்களை வாங்கவும் விற்கவும்.",
    landing_feature_campaign_title: "சமூக பிரச்சாரங்கள்",
    landing_feature_campaign_desc: "எங்கள் சுற்றுச்சூழலைப் பாதுகாக்க துப்புரவு மற்றும் மரம் நடும் பணிகளில் சேரவும்.",
    landing_feature_donate_title: "நன்கொடை",
    landing_feature_donate_desc: "தேவையுள்ளவர்களுக்கு உதவுவதற்காக துணிகள் மற்றும் புத்தகங்களை நன்கொடையாக அளியுங்கள்.",
    landing_footer_about: "Educycle பற்றி",
    landing_footer_contact: "தொடர்பு கொள்ள",
    landing_footer_rights: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",

    cart_title: "உங்கள் கூடை",
    cart_empty: "கூடை காலியாக உள்ளது",
    cart_total: "மொத்தம்",
    cart_checkout: "செக்அவுட்",
    checkout_title: "செக்அவுட்",
    pay_upi: "UPI",
    pay_card: "அட்டை",
    pay_cod: "பணம் செலுத்துதல்",
    pay_btn: "ஆர்டர் செய்யவும்",
    order_success: "ஆர்டர் உறுதி செய்யப்பட்டது!",
    order_cod_msg: "டெலிவரி செய்யும் போது பணம் தயாராக இருக்கவும்.",
    order_online_msg: "நன்றி."
  },
  gu: {
    app_name: "Educycle",
    nav_dashboard: "ડેશબોર્ડ",
    nav_profile: "મારી પ્રોફાઇલ",
    nav_settings: "સેટિંગ્સ",
    nav_marketplace: "બજાર",
    nav_sell: "વેચો",
    nav_campaigns: "ઝુંબેશ",
    nav_my_campaigns: "મારી ઝુંબેશ",
    nav_donate: "દાન",
    nav_chat: "સંદેશાઓ",
    nav_notifications: "સૂચનાઓ",
    nav_cart: "મારું કાર્ટ",
    role_switch: "મોડ",

    hero_title: "Educycle બજાર",
    hero_subtitle: "વિદ્યાર્થીઓ માટે ટકાઉ સમુદાય.",

    sell_page_title: "વેચાણ સૂચિ",
    sell_upload_image: "ફોટો અપલોડ",
    sell_generating: "AI વિશ્લેષણ...",
    sell_generate_desc: "AI-generated description",
    sell_voice_hint: "બધા વિકલ્પો અવાજ દ્વારા ભરી શકાય છે",
    form_title: "શીર્ષક",
    form_price: "કિંમત (₹)",
    form_desc: "વર્ણન",
    form_category: "શ્રેણી",
    form_submit: "સબમિટ",

    dashboard_earnings: "કુલ કમાણી",
    dashboard_transactions: "તાજેતરના વ્યવહારો",
    dashboard_sold: "વેચાયેલ",

    profile_bio: "બાયો",
    profile_name: "પૂરું નામ",
    profile_email: "ઇમેઇલ",
    profile_avatar: "પ્રોફાઇલ ફોટો",
    profile_save: "સાચવો",
    profile_edit: "ફેરફાર કરો",
    profile_cancel: "રદ કરો",
    profile_history: "ખરીદી ઇતિહાસ",
    profile_history_empty: "હજુ સુધી કોઈ વસ્તુ ખરીદી નથી.",

    settings_title: "ખાતા સેટિંગ્સ",
    settings_save: "સાચવો",
    settings_saved: "તમારા ફેરફારો સાચવવામાં આવ્યા છે.",

    campaign_join: "જોડાવું",
    campaign_register_title: "નોંધણી કરો",
    campaign_register_btn: "પુષ્ટિ કરો",
    campaign_search: "શોધો...",
    campaign_create: "+ ઝુંબેશ બનાવો",
    campaign_report: "રિપોર્ટ",
    campaign_reported: "રિપોર્ટ કરેલ",

    donate_title: "દાન ડ્રાઈવો",
    donate_btn: "દાન કરો",
    donate_form_title: "દાન ફોર્મ",
    donate_confirm: "પુષ્ટિ કરો",
    donate_item_label: "તમે શું દાન કરી રહ્યા છો?",
    donate_pickup_label: "સરનામું",
    donate_thanks: "આભાર!",

    chat_title: "ચેટ",
    chat_placeholder: "સંદેશ લખો...",
    negotiate_offer: "ઓફર કરો",
    offer_sent: "ઓફર મોકલી",
    offer_accept: "સ્વીકારો",
    offer_reject: "નકારો",
    offer_status_accepted: "સ્વીકારવામાં આવ્યું",
    offer_status_rejected: "નકારવામાં આવ્યું",

    home_welcome: "Educycle માં આપનું સ્વાગત છે",
    home_sub: "ખરીદવા, વેચવા અને પાછા આપવા માટે તમારા કેમ્પસ સમુદાય.",
    home_btn_start: "શરૂ કરો",
    home_login: "લૉગ ઇન કરો",
    home_signup: "સાઇન અપ કરો",
    auth_login_title: "તમારા ખાતામાં લૉગ ઇન કરો",
    auth_signup_title: "ખાતું બનાવો",
    auth_email: "ઇમેઇલ સરનામું",
    auth_password: "પાસવર્ડ",
    auth_name: "પૂરું નામ",
    auth_btn_login: "સાઇન ઇન કરો",
    auth_btn_signup: "સાઇન અપ કરો",
    auth_have_acc: "પહેલેથી જ એક ખાતું છે? લૉગ ઇન કરો",
    auth_no_acc: "ખાતું નથી? સાઇન અપ કરો",

    landing_features_title: "તમે શું કરી શકો છો",
    landing_feature_market_title: "વિદ્યાર્થી બજાર",
    landing_feature_market_desc: "અન્ય વિદ્યાર્થીઓ પાસેથી સીધા વપરાયેલ પુસ્તકો અને ઇલેક્ટ્રોનિક્સ ખરીદો અને વેચો.",
    landing_feature_campaign_title: "સમુદાય ઝુંબેશ",
    landing_feature_campaign_desc: "આપણા પર્યાવરણને હરિયાળું રાખવા માટે નદી સફાઈ અને વૃક્ષારોપણમાં જોડાઓ.",
    landing_feature_donate_title: "દાન ઝુંબેશ",
    landing_feature_donate_desc: "જરૂરિયાતમંદોને કપડાં અને પુસ્તકો દાન કરીને સ્થાનિક એનજીઓનું સમર્થન કરો.",
    landing_footer_about: "Educycle વિશે",
    landing_footer_contact: "સંપર્ક કરો",
    landing_footer_rights: "બધા હકો અમારી પાસે રાખેલા છે.",

    cart_title: "તમારું કાર્ટ",
    cart_empty: "કાર્ટ ખાલી છે",
    cart_total: "કુલ",
    cart_checkout: "ચેકઆઉટ",
    checkout_title: "ચેકઆઉટ",
    pay_upi: "UPI",
    pay_card: "કાર્ડ",
    pay_cod: "કેશ ઓન ડિલિવરી",
    pay_btn: "ઓર્ડર કરો",
    order_success: "ઓર્ડર કન્ફર્મ!",
    order_cod_msg: "ડિલિવરી સમયે રોકડ તૈયાર રાખો.",
    order_online_msg: "આભાર."
  }
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Engineering Mathematics Vol 2',
    description: 'Slightly used, good condition. Perfect for 2nd year students.',
    price: 350,
    category: 'Books',
    image: 'https://picsum.photos/400/400?random=1',
    sellerName: 'Rahul K.',
    status: 'available',
    reviews: [
      { id: 'r1', user: 'Sneha P.', rating: 5, comment: 'Book was in great condition!', date: '2023-10-01' },
      { id: 'r2', user: 'Vikram S.', rating: 4, comment: 'Helpful seller.', date: '2023-09-15' }
    ]
  },
  {
    id: '2',
    title: 'Scientific Calculator fx-991ES',
    description: 'Original Casio calculator, solar powered. No scratches.',
    price: 600,
    category: 'Electronics',
    image: 'https://picsum.photos/400/400?random=2',
    sellerName: 'Priya S.',
    status: 'available',
    reviews: []
  },
  {
    id: '3',
    title: 'Drafting Table for Architects',
    description: 'Adjustable height, includes parallel bar.',
    price: 2500,
    category: 'Stationary',
    image: 'https://picsum.photos/400/400?random=3',
    sellerName: 'Amit B.',
    status: 'available',
    reviews: [
        { id: 'r3', user: 'Arjun M.', rating: 5, comment: 'Very sturdy table, loved it.', date: '2023-08-20' }
    ]
  },
  {
    id: '4',
    title: 'Physics Reference Book',
    description: 'Class 12 Physics, slightly worn out cover.',
    price: 200,
    category: 'Books',
    image: 'https://picsum.photos/400/400?random=9',
    sellerName: 'You',
    status: 'sold',
    reviews: []
  }
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'c1',
    title: 'Yamuna River Cleanup Drive',
    date: 'Oct 15, 2024',
    location: 'Delhi Ghats',
    type: 'cleaning',
    participants: 120,
    image: 'https://picsum.photos/600/300?random=4',
    description: 'Join us for a massive cleanup drive at the Yamuna Ghats. Gloves and bags provided.',
    reported: false,
    keywords: ['cleaning', 'river', 'nature', 'volunteer']
  },
  {
    id: 'c2',
    title: 'Campus Recycling Marathon',
    date: 'Nov 02, 2024',
    location: 'University Main Ground',
    type: 'recycling',
    participants: 450,
    image: 'https://picsum.photos/600/300?random=5',
    description: 'Bring your old plastics and papers. Lets aim for zero waste campus!',
    reported: false,
    keywords: ['recycling', 'campus', 'waste', 'green']
  },
  {
    id: 'c3',
    title: 'Tree Planting Sunday',
    date: 'Nov 10, 2024',
    location: 'City Park Sector 5',
    type: 'planting',
    participants: 85,
    image: 'https://picsum.photos/600/300?random=6',
    description: 'Help us plant 500 saplings this Sunday. Refreshments provided.',
    reported: false,
    keywords: ['planting', 'trees', 'nature', 'park']
  }
];

export const MOCK_NGOS: NGO[] = [
  {
    id: 'n1',
    name: 'Vidya Foundation',
    focus: 'Education for Underprivileged',
    needs: ['Books', 'Stationary', 'School Bags'],
    verified: true,
    image: 'https://picsum.photos/100/100?random=7',
    description: 'We support 500+ children across 3 centers. Your old books can change a life.'
  },
  {
    id: 'n2',
    name: 'Shelter Hope',
    focus: 'Homeless & Orphanage Support',
    needs: ['Clothes', 'Blankets', 'Shoes'],
    verified: true,
    image: 'https://picsum.photos/100/100?random=8',
    description: 'Providing warmth and shelter. We desperately need winter clothes.'
  }
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  { id: 't1', itemTitle: 'Physics Textbook', date: '2024-09-28', amount: 450, status: 'Completed', buyerName: 'Anjali R.' },
  { id: 't2', itemTitle: 'Lab Coat (L)', date: '2024-10-01', amount: 200, status: 'Pending', buyerName: 'Rohan M.' },
  { id: 't3', itemTitle: 'Drafter', date: '2024-10-05', amount: 350, status: 'Completed', buyerName: 'Suresh P.' },
];

export const MOCK_CHATS: ChatContact[] = [
  { id: 'system', name: 'Educycle System', lastMessage: 'Welcome to Educycle!', unread: 0, avatar: 'https://ui-avatars.com/api/?name=Educycle&background=16a34a&color=fff', isSystem: true },
  { id: 'u1', name: 'Rahul K.', lastMessage: 'Is the calculator still available?', unread: 2, avatar: 'https://i.pravatar.cc/150?u=u1' },
  { id: 'u2', name: 'Priya S.', lastMessage: 'I can pick it up tomorrow.', unread: 0, avatar: 'https://i.pravatar.cc/150?u=u2' },
  { id: 'u3', name: 'Amit B.', lastMessage: 'Thanks for the book!', unread: 1, avatar: 'https://i.pravatar.cc/150?u=u3' },
];
